### PR TITLE
Extracted Classes

### PR DESCRIPTION
**Pull request by praij90**
Extracted all classes into separate code and header files (.cpp, .h resp.). Additionally slightly restructured file location to accommodate future changes.

*Note: made a faulty pull request earlier with the same title, please ignore.*

### CODE REVIEW

**Comment by praij90** [comment]
Hi Guys ang Gals,

I've been working with your controller for some time and I must would like to give you my compliments on its functionality. Unfortunately however useful the controller is, modification to it are quite difficult due to the single file container. I've taken the liberty of restructuring the code (as can be seen in the above commit) in order to make life easier.
If you agree with the changes to your code I would be honoured  to contribute to your project through this merge request.

Happy coding,
    -Paul

**Comment by wunderkammer-laboratory** [comment]
The controller's classes are implementation details, not an API, which is why they are not exposed in header files. Please describe the types of extensions to the controller you are trying to make that require access to internal classes.

**Comment by praij90** [comment]
Hi,

What I've done locally is added feed forward tools to the ros_control toolbox. Then I implemented those tools on your controller (See pull request 49 of the ros_control/control_toolbox repos). Specifically the PIDJoint class, which I copied and renamed to HybridJoint indicating both PID and FF capabilities. Naturally some additional changes had to be made to load the parameters in the tools. 

This pull request is in preparation of the before mentioned additions. Moreover I believe exposing the sub classes provides better insight into how your code works by the breakdown into bite sized chunks making it more accessible to others.

**Comment by wunderkammer-laboratory** [comment]
@adolfo-rt, I designed the steered-wheel base controller to support effort, position, and velocity interfaces for all joints, using JointTrajectoryController as an example. PID controller gains can be specified for effort-controlled joints and velocity-controlled steering joints. This pull request is related to implementing feed-forward control in addition to PID control. I am now wondering whether the base controller should have been designed to support only the position interface for steering joints, and the velocity interface for axle joints. The differential drive controller, for example, supports the velocity interface only. Should PID/FF/you-name-it control really be performed in a relatively "high-level" (i.e. it should really just point each wheel in the correct direction and set its angular velocity) controller such as the base controller, or should such control be performed in the controller manager. By "controller manager," I'm referring to classes derived from  hardware_interface::RobotHW and controller_manager::ControllerManager.

If I follow the path required by this pull request, the base controller will need to be modified every time someone wants to add a new control scheme. I don't think this is the right place to do that. I think there was discussion at one time about metacontrollers, but I don't know what came of that.

**Comment by adolfo-rt** [comment]
`diff_drive_controller` only supports velocity controlled wheels, because nobody has found it useful to support more interfaces. It could quite easily support effort joints as well.

Generally speaking, I'd suggest supporting the interfaces that:
* are part of your usecase, so they get well tested, and
* are part of other common usecases, especially if you're looking for your code to be used by others

For this particular case, position or effort for steering; and velocity or effort for axles seem reasonable. I see no harm if you already support more than that, except for the additional maintenance effort that might bring.

**Comment by wunderkammer-laboratory** [comment]
I've decided not to merge this pull request. It appears that the changes exist only to change the style of the code rather than adding functionality to it. I understand that the changes in this PR make the code more amenable to having feed-forward control added to it, but I prefer that changes to code be minimal. Refactoring of code is a last resort. I suggest that you thoroughly test the feed-forward code in your fork of this package, then submit a pull request that changes as little code as possible.

**Pull request closed without merging**
